# Test Params
############################################
stimulus_time_duration_pretest: 1.5 # DO NOT CHANGE.

subject: "123abc"
subject_number: 123 # Change this field
age: 23 # Change this field
sex: "female" # Change this field. Either "male" or "female"
condition: "HCL" # Change this field. Either "HCL" or "LCL"
# test_reps: 1  # you can specify this yourself, otherwise the test runs
                # for 16 minutes.
